import React, { useRef, useCallback, useState } from 'react';
import {
  Animated,
  Image,
  ImageSourcePropType,
  Pressable,
  StyleSheet,
  Text,
  View,
  ViewStyle,
} from 'react-native';
import { SURFACE, getPressSpring } from '../../theme/surfaces';
import {
  getPixelSkin,
  BTN_CAP_DP,
  BTN_MD_DP,
  BTN_LG_DP,
  BTN_SHADOW_DP,
} from '../../theme/pixelSkin.generated';
import { ThreeSliceStrip } from './NineSlice';
import { getSettingsSync } from '../../services/settings';
import { playUiSound, type UiSoundKind } from '../../services/uiSound';
import { PIXEL_FONT_BOLD } from '../../theme/fonts';

export type CandyButtonVariant = 'primary' | 'amber' | 'secondary' | 'quiet';

interface CandyButtonProps {
  label: string;
  onPress: () => void;
  phase: number;
  /**
   * primary — the one strong CTA on a surface (amber pixel bevel; the cozy
   *           convention keeps exactly one saturated warm primary per screen)
   * amber   — prices / claims (same amber bevel as primary by design: the
   *           accent hue IS the currency color)
   * secondary — wood-trimmed parchment bevel (supporting actions)
   * quiet   — soft parchment bevel (dismiss / low-emphasis; cozy games never
   *           use borderless text buttons)
   */
  variant?: CandyButtonVariant;
  disabled?: boolean;
  /**
   * Set when the button sits on a host panel that is ALREADY dark at phases
   * below 3 (the home modals use getDialogueTheme, which darkens at phase 2 —
   * one phase before getSurfaceTheme). Maps the skin to the dark material.
   */
  hostDark?: boolean;
  /** Optional ui-sprite icon rendered left of the label. */
  icon?: ImageSourcePropType;
  size?: 'md' | 'lg';
  style?: ViewStyle;
  accessibilityLabel?: string;
  /**
   * UI sound on press. Defaults to a confirm 'tap' for primary/amber and a
   * softer 'selection' tick for secondary/quiet. Pass 'none' to stay silent
   * (e.g. a button whose handler already plays a semantic sound).
   */
  soundKind?: UiSoundKind | 'none';
}

/**
 * Cottage pixel button — a 3-slice pixel-bevel strip (generated by
 * scripts/tools/generateUiPanels.mjs) with a baked cast shadow. Pressing
 * swaps to the "down" sprite (light falls into the socket) and the label
 * travels down SURFACE.pressTravel, springing back with phase weight.
 * Reduced motion pins the travel; the sprite swap remains (it is a state,
 * not an animation).
 */
export const CandyButton: React.FC<CandyButtonProps> = ({
  label,
  onPress,
  phase,
  variant = 'primary',
  disabled = false,
  hostDark = false,
  icon,
  size = 'md',
  style,
  accessibilityLabel,
  soundKind,
}) => {
  const skin = getPixelSkin(phase, hostDark);
  const reducedMotion = getSettingsSync().reducedMotion;
  const travel = useRef(new Animated.Value(0)).current;
  const [pressed, setPressed] = useState(false);

  const handlePress = useCallback(() => {
    if (soundKind !== 'none') {
      playUiSound(soundKind ?? (variant === 'secondary' || variant === 'quiet' ? 'selection' : 'tap'));
    }
    onPress();
  }, [onPress, soundKind, variant]);

  const skinVariant = variant === 'amber' ? 'primary' : variant;
  const buttonSkin = skin.buttons[skinVariant][size];
  const ink = skin.ink[skinVariant];
  const stripHeight = (size === 'lg' ? BTN_LG_DP : BTN_MD_DP) + BTN_SHADOW_DP;

  const handlePressIn = useCallback(() => {
    setPressed(true);
    if (reducedMotion) return;
    Animated.timing(travel, { toValue: 1, duration: 60, useNativeDriver: true }).start();
  }, [travel, reducedMotion]);

  const handlePressOut = useCallback(() => {
    setPressed(false);
    if (reducedMotion) return;
    const spring = getPressSpring(phase);
    Animated.spring(travel, { toValue: 0, ...spring, useNativeDriver: true }).start();
  }, [travel, phase, reducedMotion]);

  const translateY = travel.interpolate({
    inputRange: [0, 1],
    outputRange: [0, SURFACE.pressTravel],
  });

  return (
    <Pressable
      onPress={disabled ? undefined : handlePress}
      onPressIn={handlePressIn}
      onPressOut={handlePressOut}
      disabled={disabled}
      accessibilityRole="button"
      accessibilityLabel={accessibilityLabel ?? label}
      accessibilityState={{ disabled }}
      style={[{ height: stripHeight, minWidth: BTN_CAP_DP * 2 + 24 }, disabled && styles.disabled, style]}
      // Disabled dims the whole button with opacity. Android applies group
      // opacity PER-VIEW, so the strip's deliberate 1dp cap/middle overlap
      // double-blends into a more-opaque vertical sliver at both cap joints
      // (the "thin vertical lines" on In Progress / unaffordable buttons).
      // Offscreen compositing fades the subtree as one layer.
      needsOffscreenAlphaCompositing={disabled}
      hitSlop={variant === 'quiet' ? { top: 4, bottom: 4, left: 6, right: 6 } : undefined}
    >
      <ThreeSliceStrip skin={pressed ? buttonSkin.down : buttonSkin.up} capDp={BTN_CAP_DP} />
      <Animated.View
        style={[
          styles.content,
          // The baked shadow row sits below the button body — keep the label
          // centered in the body, not the full strip.
          { paddingBottom: BTN_SHADOW_DP, transform: [{ translateY }] },
        ]}
      >
        {icon ? <Image source={icon} style={styles.icon} resizeMode="contain" /> : null}
        <Text
          numberOfLines={1}
          style={[
            styles.label,
            size === 'lg' && styles.labelLg,
            variant === 'quiet' && styles.quietLabel,
            { color: ink },
          ]}
        >
          {label}
        </Text>
      </Animated.View>
    </Pressable>
  );
};

const styles = StyleSheet.create({
  content: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 16,
  },
  disabled: {
    opacity: 0.45,
  },
  icon: {
    width: 18,
    height: 18,
    marginRight: 8,
  },
  label: {
    fontFamily: PIXEL_FONT_BOLD,
    fontSize: 16,
    fontWeight: '800',
    letterSpacing: 0.6,
    textAlign: 'center',
  },
  labelLg: {
    fontSize: 18,
  },
  quietLabel: {
    fontFamily: PIXEL_FONT_BOLD,
    fontWeight: '700',
    fontSize: 15,
  },
});

export default CandyButton;
