import React from 'react';
import { StyleSheet, Text, View, ViewStyle } from 'react-native';
import {
  getPixelSkin,
  PLAQUE_H_DP,
  PLAQUE_CAP_DP,
} from '../../theme/pixelSkin.generated';
import { SURFACE } from '../../theme/surfaces';
import { ThreeSliceStrip } from './NineSlice';

interface PixelPlaqueProps {
  phase: number;
  /** Plaque label — rendered ALL-CAPS with the classic hard pixel shadow. */
  label: string;
  hostDark?: boolean;
  style?: ViewStyle;
}

/**
 * Wooden nameplate for section headers and titles — a 3-slice dark-wood
 * plaque with nail heads in its end caps (generated by
 * scripts/tools/generateUiPanels.mjs). Overlap a parent panel's top edge
 * (negative marginTop) to read as a nameplate nailed onto the furniture.
 */
export const PixelPlaque: React.FC<PixelPlaqueProps> = ({ phase, label, hostDark = false, style }) => {
  const skin = getPixelSkin(phase, hostDark);
  return (
    <View style={[styles.plaque, style]}>
      <ThreeSliceStrip skin={skin.plaque} capDp={PLAQUE_CAP_DP} />
      <Text numberOfLines={1} style={[styles.label, { color: skin.ink.plaque }]}>
        {label.toUpperCase()}
      </Text>
    </View>
  );
};

const styles = StyleSheet.create({
  plaque: {
    height: PLAQUE_H_DP,
    alignSelf: 'center',
    justifyContent: 'center',
    paddingHorizontal: PLAQUE_CAP_DP + 8,
    minWidth: PLAQUE_CAP_DP * 2 + 40,
  },
  label: {
    fontSize: 13,
    fontWeight: '900',
    letterSpacing: SURFACE.sectionLetterSpacing,
    textAlign: 'center',
    // Hard 1-art-px shadow, zero blur — the classic pixel label treatment.
    textShadowColor: 'rgba(20, 10, 6, 0.5)',
    textShadowOffset: { width: 0, height: 3 },
    textShadowRadius: 0,
  },
});

export default PixelPlaque;
