import React from 'react';
import { StyleSheet, Text, View, ViewStyle } from 'react-native';
import {
  getPixelSkin,
  PLAQUE_H_DP,
  PLAQUE_CAP_DP,
} from '../../theme/pixelSkin.generated';
import { SURFACE } from '../../theme/surfaces';
import { ThreeSliceStrip } from './NineSlice';
import { PIXEL_FONT_BOLD } from '../../theme/fonts';

interface PixelPlaqueProps {
  phase: number;
  /** Plaque label — rendered ALL-CAPS with the classic hard pixel shadow. */
  label: string;
  hostDark?: boolean;
  style?: ViewStyle;
  /**
   * Uniform downscale for space-constrained hosts (e.g. the small in-house room
   * labels, where a full 42dp plaque would swamp a ~123dp room). Scales height,
   * end caps, font, and padding TOGETHER by the same factor, so the 3-slice
   * pixel sprite's aspect ratio (capDp / height) is preserved and the wood never
   * distorts. Default 1 — every existing full-size plaque is unchanged.
   */
  scale?: number;
}

/**
 * Wooden nameplate for section headers and titles — a 3-slice dark-wood
 * plaque with nail heads in its end caps (generated by
 * scripts/tools/generateUiPanels.mjs). Overlap a parent panel's top edge
 * (negative marginTop) to read as a nameplate nailed onto the furniture.
 */
export const PixelPlaque: React.FC<PixelPlaqueProps> = ({ phase, label, hostDark = false, style, scale = 1 }) => {
  const skin = getPixelSkin(phase, hostDark);
  const capDp = PLAQUE_CAP_DP * scale;
  return (
    <View
      style={[
        styles.plaque,
        {
          height: PLAQUE_H_DP * scale,
          paddingHorizontal: capDp + 8 * scale,
          minWidth: capDp * 2 + 40 * scale,
        },
        style,
      ]}
    >
      <ThreeSliceStrip skin={skin.plaque} capDp={capDp} />
      <Text
        numberOfLines={1}
        style={[styles.label, { color: skin.ink.plaque, fontSize: 14 * scale, textShadowOffset: { width: 0, height: 3 * scale } }]}
      >
        {label.toUpperCase()}
      </Text>
    </View>
  );
};

const styles = StyleSheet.create({
  plaque: {
    alignSelf: 'center',
    justifyContent: 'center',
  },
  label: {
    fontFamily: PIXEL_FONT_BOLD,
    fontWeight: '900',
    letterSpacing: SURFACE.sectionLetterSpacing,
    textAlign: 'center',
    // Hard 1-art-px shadow, zero blur — the classic pixel label treatment.
    textShadowColor: 'rgba(20, 10, 6, 0.5)',
    textShadowRadius: 0,
  },
});

export default PixelPlaque;
