import fs from 'node:fs';
const beats=JSON.parse(fs.readFileSync(new URL('story-art-inventory.json',import.meta.url)));
const settings={cup:'a friendly cottage kitchen and hearth, early bright days',echo:'an old round dark stone well-like ritual pit beneath a woodland cottage; no monster visible',witness:'the cottage writing desk and shared table at dusk',supper:'a woodland cottage kitchen and supper table with soup, warm hearth in uneasy dusk',plan:'the workshop, foundations, library and watch-window of a woodland cottage, uncertain evening',shelter:'the cottage doorway, workshop and outward garden gate at dusk',plum:'a small woodland cottage aquarium for fish, calm blue water, sand and water plants',plum_recruited:'a small woodland cottage aquarium for fish, calm blue water, sand and water plants',record:'a cottage writing desk with a leather ledger and cream paper, a late-night lamp',seeds:'a small wooden garden gate, seed tin, and a forest footpath leading out of a woodland cottage garden in moonlight',promise:'an intimate woodland cottage hearth with two wooden chairs and a cup, quiet blue midnight outside',returned:'an intimate woodland cottage aquarium, blue midnight water and quiet reflective shadows',council:'a woodland cottage common room at midnight, household belongings and the final moment before an otherworldly welcome, no monster visible',after:'the woodland cottage and its gate in quiet morning sunlight after a difficult night',reply:'the cottage hearth and two chairs in gentle morning light with room to sit apart',old_mark:'a woodland cottage in fresh bright morning; one little domestic object carries an old memory'};
const overrides={
 'cup-02':'Close study of two handmade cups on a wooden serving tray: one with a small chip in its HANDLE, one with a charming lopsided painted orange flower. Side-by-side comparison; no drinks being poured.',
 'cup-03':'A single handmade cream cup with an amusing crooked orange flower painting, next to a tiny paintbrush and orange paint; the flower is endearingly ambiguous, originally meant as a fox. Tight playful still-life.',
 'cup-04':'The chosen crooked-flower cup is being filled with hot cocoa from a small saucepan, steam curling warmly; a wooden spoon and a few cocoa spills capture the brave taste test.',
 'cup-05':'The chipped-HANDLE cup has been moved across the table to the other chair. The flower cup remains near the viewer. Wide side view emphasizing this changed arrangement, two chairs, warm fire.',
 'cup-06':'IMPORTANT: the cup RIM is perfectly intact and round; a small wedge is missing from the OUTSIDE of its HANDLE only. One chipped-HANDLE ceramic cup is nestled securely between two simple orange fox forepaws on a wooden tabletop; show just the paws and cup, a close tender view of an imperfect object fitting comfortably.',
 'cup-07':'A cocoa saucepan has been put away onto a cottage kitchen shelf. A little closed cocoa jar sits beside it; a steaming tea cup waits on the counter below. A tidy, generous kitchen moment.',
 'plum-01':'A single elderly tiny orange-gold fish called PLUM with a worried face and one small notch bitten out of his fin swims his first lap in an intimate cottage aquarium. Clear profile near aquarium plants, warm approachable expression, no axolotl character.',
 'plum-02':'The same elderly small orange-gold PLUM fish with worried brow and a tiny notched fin touches a crooked large air bubble with his nose, then begins turning toward the glass; gentle comic underwater close view.',
 'plum-03':'Close portrait of the elderly small orange-gold PLUM fish, with delicate worn fin edges and a tiny notch in one fin, worried face, quiet blue water and a few old water-plant leaves; affectionate reflection on age.',
 'plum-04':'Outside an aquarium pane, one tiny pink axolotl hand follows a little elderly orange-gold fish swimming just inside the glass; they are close but never touch, with the glass reflection visibly separating them.',
};
for(const beat of beats){
 let setting=settings[beat.scene];
 if((beat.scene==='plum'&&Number(beat.id.split('-')[1])>=5)||(beat.scene==='returned'&&Number(beat.id.split('-')[1])>=7))setting='a woodland cottage hearth, an imperfect ceramic cup and wooden chairs, with a ritual stone pit below the house';
 const prompt=`Use case: illustration-story. Asset type: one finished landscape 16:9 story-page illustration for WordShift, an intimate woodland-cottage pixel-art game. Depict this exact authored narrative moment: "${beat.samples[0]}". Setting: ${setting}. ${overrides[beat.id]??''} Create a distinct composition centered on the action or emotional detail in THIS sentence; do not reproduce a generic two-cups-and-notebook table. For spoken abstract thoughts, illustrate the specific setting, relevant object, and relationship described, without adding plot events. Visual style: sophisticated 16-bit storybook pixel art, clearly visible carefully placed pixel clusters, dimensional amber light and cool blue shadows, walnut wood and moss-green textiles, tactile handmade objects, strong readable silhouette at phone size. Rich finished art, not vector icons and not photorealism. No full animal characters (the game adds its exact character portrait separately); a hand or paw only if needed by the stated action. Do not add teacups unless this beat specifically concerns one. No UI, caption, border, collage, watermark, horror eyes, monster or invented plot. ABSOLUTELY NO TEXT: never write the supplied narrative sentence, dialogue, letters, numbers, words, quotes, glyphs, signs, or decorative typography anywhere in the illustration. Narrative paper and notebooks show subtle ink-like marks ONLY, with no readable or invented characters. A spoken line is an art direction, NEVER lettering. For ritual words use unlettered warm wooden word tiles or a quiet reflection, NEVER invent a word. Single landscape image, no split panels. Keep the important subject inside the middle 85% so nothing is clipped.`;
 beat.prompt=prompt;
}
fs.writeFileSync(new URL('story-art-prompts.json',import.meta.url),JSON.stringify(beats,null,2)+'\n');console.log(beats.length+' separate image prompts');
