// AUTO-GENERATED by scripts/tools/generateUiPanels.mjs — do not edit.
// Cottage pixel UI skin registry: 9-slice frames + 3-slice buttons/plaques.
import { ImageSourcePropType } from 'react-native';

export interface FrameSkin { tl: ImageSourcePropType; tr: ImageSourcePropType; bl: ImageSourcePropType; br: ImageSourcePropType; top: ImageSourcePropType; bottom: ImageSourcePropType; left: ImageSourcePropType; right: ImageSourcePropType; }
export interface ThreeSlice { l: ImageSourcePropType; m: ImageSourcePropType; r: ImageSourcePropType; }
export interface ButtonSkin { up: ThreeSlice; down: ThreeSlice; }
export interface PixelSkin { panel: FrameSkin; card: FrameSkin; buttons: { primary: { md: ButtonSkin; lg: ButtonSkin }; secondary: { md: ButtonSkin; lg: ButtonSkin }; quiet: { md: ButtonSkin; lg: ButtonSkin } }; plaque: ThreeSlice; fill: string; fillCard: string; /** Painted-inlay second hue per skin (structural accent, never an action color). */ accent: string; accentLo: string; ink: { primary: string; secondary: string; quiet: string; plaque: string }; }

/** dp sizes (1 art-px = 3 dp; PNGs are baked at 9 real px per art-px). */
export const PANEL_CORNER_DP = 36;
export const PANEL_EDGE_DP = 30;
export const CARD_CORNER_DP = 21;
export const CARD_EDGE_DP = 18;
export const BTN_CAP_DP = 24;
export const BTN_MD_DP = 42;
export const BTN_LG_DP = 57;
export const BTN_SHADOW_DP = 3;
export const PLAQUE_H_DP = 42;
export const PLAQUE_CAP_DP = 30;

export const PIXEL_SKINS: Record<'bright' | 'dusk' | 'storm' | 'dark' | 'serene', PixelSkin> = {
  bright: {
    panel: { tl: require('../../assets/ui/panels/bright/panel_tl.png'), tr: require('../../assets/ui/panels/bright/panel_tr.png'), bl: require('../../assets/ui/panels/bright/panel_bl.png'), br: require('../../assets/ui/panels/bright/panel_br.png'), top: require('../../assets/ui/panels/bright/panel_top.png'), bottom: require('../../assets/ui/panels/bright/panel_bottom.png'), left: require('../../assets/ui/panels/bright/panel_left.png'), right: require('../../assets/ui/panels/bright/panel_right.png') },
    card: { tl: require('../../assets/ui/panels/bright/card_tl.png'), tr: require('../../assets/ui/panels/bright/card_tr.png'), bl: require('../../assets/ui/panels/bright/card_bl.png'), br: require('../../assets/ui/panels/bright/card_br.png'), top: require('../../assets/ui/panels/bright/card_top.png'), bottom: require('../../assets/ui/panels/bright/card_bottom.png'), left: require('../../assets/ui/panels/bright/card_left.png'), right: require('../../assets/ui/panels/bright/card_right.png') },
    buttons: {
      primary: { md: { up: { l: require('../../assets/ui/panels/bright/btn_primary_md_up_l.png'), m: require('../../assets/ui/panels/bright/btn_primary_md_up_m.png'), r: require('../../assets/ui/panels/bright/btn_primary_md_up_r.png') }, down: { l: require('../../assets/ui/panels/bright/btn_primary_md_down_l.png'), m: require('../../assets/ui/panels/bright/btn_primary_md_down_m.png'), r: require('../../assets/ui/panels/bright/btn_primary_md_down_r.png') } }, lg: { up: { l: require('../../assets/ui/panels/bright/btn_primary_lg_up_l.png'), m: require('../../assets/ui/panels/bright/btn_primary_lg_up_m.png'), r: require('../../assets/ui/panels/bright/btn_primary_lg_up_r.png') }, down: { l: require('../../assets/ui/panels/bright/btn_primary_lg_down_l.png'), m: require('../../assets/ui/panels/bright/btn_primary_lg_down_m.png'), r: require('../../assets/ui/panels/bright/btn_primary_lg_down_r.png') } } },
      secondary: { md: { up: { l: require('../../assets/ui/panels/bright/btn_secondary_md_up_l.png'), m: require('../../assets/ui/panels/bright/btn_secondary_md_up_m.png'), r: require('../../assets/ui/panels/bright/btn_secondary_md_up_r.png') }, down: { l: require('../../assets/ui/panels/bright/btn_secondary_md_down_l.png'), m: require('../../assets/ui/panels/bright/btn_secondary_md_down_m.png'), r: require('../../assets/ui/panels/bright/btn_secondary_md_down_r.png') } }, lg: { up: { l: require('../../assets/ui/panels/bright/btn_secondary_lg_up_l.png'), m: require('../../assets/ui/panels/bright/btn_secondary_lg_up_m.png'), r: require('../../assets/ui/panels/bright/btn_secondary_lg_up_r.png') }, down: { l: require('../../assets/ui/panels/bright/btn_secondary_lg_down_l.png'), m: require('../../assets/ui/panels/bright/btn_secondary_lg_down_m.png'), r: require('../../assets/ui/panels/bright/btn_secondary_lg_down_r.png') } } },
      quiet: { md: { up: { l: require('../../assets/ui/panels/bright/btn_quiet_md_up_l.png'), m: require('../../assets/ui/panels/bright/btn_quiet_md_up_m.png'), r: require('../../assets/ui/panels/bright/btn_quiet_md_up_r.png') }, down: { l: require('../../assets/ui/panels/bright/btn_quiet_md_down_l.png'), m: require('../../assets/ui/panels/bright/btn_quiet_md_down_m.png'), r: require('../../assets/ui/panels/bright/btn_quiet_md_down_r.png') } }, lg: { up: { l: require('../../assets/ui/panels/bright/btn_quiet_lg_up_l.png'), m: require('../../assets/ui/panels/bright/btn_quiet_lg_up_m.png'), r: require('../../assets/ui/panels/bright/btn_quiet_lg_up_r.png') }, down: { l: require('../../assets/ui/panels/bright/btn_quiet_lg_down_l.png'), m: require('../../assets/ui/panels/bright/btn_quiet_lg_down_m.png'), r: require('../../assets/ui/panels/bright/btn_quiet_lg_down_r.png') } } },
    },
    plaque: { l: require('../../assets/ui/panels/bright/plaque_l.png'), m: require('../../assets/ui/panels/bright/plaque_m.png'), r: require('../../assets/ui/panels/bright/plaque_r.png') },
    fill: '#F3E2BF',
    fillCard: '#EBD8B2',
    accent: '#6E9A4B',
    accentLo: '#527A36',
    ink: { primary: '#3B2416', secondary: '#4A3222', quiet: '#6B4A2F', plaque: '#FBF0D9' },
  },
  dusk: {
    panel: { tl: require('../../assets/ui/panels/dusk/panel_tl.png'), tr: require('../../assets/ui/panels/dusk/panel_tr.png'), bl: require('../../assets/ui/panels/dusk/panel_bl.png'), br: require('../../assets/ui/panels/dusk/panel_br.png'), top: require('../../assets/ui/panels/dusk/panel_top.png'), bottom: require('../../assets/ui/panels/dusk/panel_bottom.png'), left: require('../../assets/ui/panels/dusk/panel_left.png'), right: require('../../assets/ui/panels/dusk/panel_right.png') },
    card: { tl: require('../../assets/ui/panels/dusk/card_tl.png'), tr: require('../../assets/ui/panels/dusk/card_tr.png'), bl: require('../../assets/ui/panels/dusk/card_bl.png'), br: require('../../assets/ui/panels/dusk/card_br.png'), top: require('../../assets/ui/panels/dusk/card_top.png'), bottom: require('../../assets/ui/panels/dusk/card_bottom.png'), left: require('../../assets/ui/panels/dusk/card_left.png'), right: require('../../assets/ui/panels/dusk/card_right.png') },
    buttons: {
      primary: { md: { up: { l: require('../../assets/ui/panels/dusk/btn_primary_md_up_l.png'), m: require('../../assets/ui/panels/dusk/btn_primary_md_up_m.png'), r: require('../../assets/ui/panels/dusk/btn_primary_md_up_r.png') }, down: { l: require('../../assets/ui/panels/dusk/btn_primary_md_down_l.png'), m: require('../../assets/ui/panels/dusk/btn_primary_md_down_m.png'), r: require('../../assets/ui/panels/dusk/btn_primary_md_down_r.png') } }, lg: { up: { l: require('../../assets/ui/panels/dusk/btn_primary_lg_up_l.png'), m: require('../../assets/ui/panels/dusk/btn_primary_lg_up_m.png'), r: require('../../assets/ui/panels/dusk/btn_primary_lg_up_r.png') }, down: { l: require('../../assets/ui/panels/dusk/btn_primary_lg_down_l.png'), m: require('../../assets/ui/panels/dusk/btn_primary_lg_down_m.png'), r: require('../../assets/ui/panels/dusk/btn_primary_lg_down_r.png') } } },
      secondary: { md: { up: { l: require('../../assets/ui/panels/dusk/btn_secondary_md_up_l.png'), m: require('../../assets/ui/panels/dusk/btn_secondary_md_up_m.png'), r: require('../../assets/ui/panels/dusk/btn_secondary_md_up_r.png') }, down: { l: require('../../assets/ui/panels/dusk/btn_secondary_md_down_l.png'), m: require('../../assets/ui/panels/dusk/btn_secondary_md_down_m.png'), r: require('../../assets/ui/panels/dusk/btn_secondary_md_down_r.png') } }, lg: { up: { l: require('../../assets/ui/panels/dusk/btn_secondary_lg_up_l.png'), m: require('../../assets/ui/panels/dusk/btn_secondary_lg_up_m.png'), r: require('../../assets/ui/panels/dusk/btn_secondary_lg_up_r.png') }, down: { l: require('../../assets/ui/panels/dusk/btn_secondary_lg_down_l.png'), m: require('../../assets/ui/panels/dusk/btn_secondary_lg_down_m.png'), r: require('../../assets/ui/panels/dusk/btn_secondary_lg_down_r.png') } } },
      quiet: { md: { up: { l: require('../../assets/ui/panels/dusk/btn_quiet_md_up_l.png'), m: require('../../assets/ui/panels/dusk/btn_quiet_md_up_m.png'), r: require('../../assets/ui/panels/dusk/btn_quiet_md_up_r.png') }, down: { l: require('../../assets/ui/panels/dusk/btn_quiet_md_down_l.png'), m: require('../../assets/ui/panels/dusk/btn_quiet_md_down_m.png'), r: require('../../assets/ui/panels/dusk/btn_quiet_md_down_r.png') } }, lg: { up: { l: require('../../assets/ui/panels/dusk/btn_quiet_lg_up_l.png'), m: require('../../assets/ui/panels/dusk/btn_quiet_lg_up_m.png'), r: require('../../assets/ui/panels/dusk/btn_quiet_lg_up_r.png') }, down: { l: require('../../assets/ui/panels/dusk/btn_quiet_lg_down_l.png'), m: require('../../assets/ui/panels/dusk/btn_quiet_lg_down_m.png'), r: require('../../assets/ui/panels/dusk/btn_quiet_lg_down_r.png') } } },
    },
    plaque: { l: require('../../assets/ui/panels/dusk/plaque_l.png'), m: require('../../assets/ui/panels/dusk/plaque_m.png'), r: require('../../assets/ui/panels/dusk/plaque_r.png') },
    fill: '#E6D0A9',
    fillCard: '#DCC49B',
    accent: '#A9535C',
    accentLo: '#873E46',
    ink: { primary: '#33201E', secondary: '#43301F', quiet: '#64492E', plaque: '#F2D2A9' },
  },
  storm: {
    panel: { tl: require('../../assets/ui/panels/storm/panel_tl.png'), tr: require('../../assets/ui/panels/storm/panel_tr.png'), bl: require('../../assets/ui/panels/storm/panel_bl.png'), br: require('../../assets/ui/panels/storm/panel_br.png'), top: require('../../assets/ui/panels/storm/panel_top.png'), bottom: require('../../assets/ui/panels/storm/panel_bottom.png'), left: require('../../assets/ui/panels/storm/panel_left.png'), right: require('../../assets/ui/panels/storm/panel_right.png') },
    card: { tl: require('../../assets/ui/panels/storm/card_tl.png'), tr: require('../../assets/ui/panels/storm/card_tr.png'), bl: require('../../assets/ui/panels/storm/card_bl.png'), br: require('../../assets/ui/panels/storm/card_br.png'), top: require('../../assets/ui/panels/storm/card_top.png'), bottom: require('../../assets/ui/panels/storm/card_bottom.png'), left: require('../../assets/ui/panels/storm/card_left.png'), right: require('../../assets/ui/panels/storm/card_right.png') },
    buttons: {
      primary: { md: { up: { l: require('../../assets/ui/panels/storm/btn_primary_md_up_l.png'), m: require('../../assets/ui/panels/storm/btn_primary_md_up_m.png'), r: require('../../assets/ui/panels/storm/btn_primary_md_up_r.png') }, down: { l: require('../../assets/ui/panels/storm/btn_primary_md_down_l.png'), m: require('../../assets/ui/panels/storm/btn_primary_md_down_m.png'), r: require('../../assets/ui/panels/storm/btn_primary_md_down_r.png') } }, lg: { up: { l: require('../../assets/ui/panels/storm/btn_primary_lg_up_l.png'), m: require('../../assets/ui/panels/storm/btn_primary_lg_up_m.png'), r: require('../../assets/ui/panels/storm/btn_primary_lg_up_r.png') }, down: { l: require('../../assets/ui/panels/storm/btn_primary_lg_down_l.png'), m: require('../../assets/ui/panels/storm/btn_primary_lg_down_m.png'), r: require('../../assets/ui/panels/storm/btn_primary_lg_down_r.png') } } },
      secondary: { md: { up: { l: require('../../assets/ui/panels/storm/btn_secondary_md_up_l.png'), m: require('../../assets/ui/panels/storm/btn_secondary_md_up_m.png'), r: require('../../assets/ui/panels/storm/btn_secondary_md_up_r.png') }, down: { l: require('../../assets/ui/panels/storm/btn_secondary_md_down_l.png'), m: require('../../assets/ui/panels/storm/btn_secondary_md_down_m.png'), r: require('../../assets/ui/panels/storm/btn_secondary_md_down_r.png') } }, lg: { up: { l: require('../../assets/ui/panels/storm/btn_secondary_lg_up_l.png'), m: require('../../assets/ui/panels/storm/btn_secondary_lg_up_m.png'), r: require('../../assets/ui/panels/storm/btn_secondary_lg_up_r.png') }, down: { l: require('../../assets/ui/panels/storm/btn_secondary_lg_down_l.png'), m: require('../../assets/ui/panels/storm/btn_secondary_lg_down_m.png'), r: require('../../assets/ui/panels/storm/btn_secondary_lg_down_r.png') } } },
      quiet: { md: { up: { l: require('../../assets/ui/panels/storm/btn_quiet_md_up_l.png'), m: require('../../assets/ui/panels/storm/btn_quiet_md_up_m.png'), r: require('../../assets/ui/panels/storm/btn_quiet_md_up_r.png') }, down: { l: require('../../assets/ui/panels/storm/btn_quiet_md_down_l.png'), m: require('../../assets/ui/panels/storm/btn_quiet_md_down_m.png'), r: require('../../assets/ui/panels/storm/btn_quiet_md_down_r.png') } }, lg: { up: { l: require('../../assets/ui/panels/storm/btn_quiet_lg_up_l.png'), m: require('../../assets/ui/panels/storm/btn_quiet_lg_up_m.png'), r: require('../../assets/ui/panels/storm/btn_quiet_lg_up_r.png') }, down: { l: require('../../assets/ui/panels/storm/btn_quiet_lg_down_l.png'), m: require('../../assets/ui/panels/storm/btn_quiet_lg_down_m.png'), r: require('../../assets/ui/panels/storm/btn_quiet_lg_down_r.png') } } },
    },
    plaque: { l: require('../../assets/ui/panels/storm/plaque_l.png'), m: require('../../assets/ui/panels/storm/plaque_m.png'), r: require('../../assets/ui/panels/storm/plaque_r.png') },
    fill: '#CDB289',
    fillCard: '#C2A67D',
    accent: '#5F6E96',
    accentLo: '#485577',
    ink: { primary: '#2A1A10', secondary: '#2F1F14', quiet: '#4A3626', plaque: '#E48B6D' },
  },
  dark: {
    panel: { tl: require('../../assets/ui/panels/dark/panel_tl.png'), tr: require('../../assets/ui/panels/dark/panel_tr.png'), bl: require('../../assets/ui/panels/dark/panel_bl.png'), br: require('../../assets/ui/panels/dark/panel_br.png'), top: require('../../assets/ui/panels/dark/panel_top.png'), bottom: require('../../assets/ui/panels/dark/panel_bottom.png'), left: require('../../assets/ui/panels/dark/panel_left.png'), right: require('../../assets/ui/panels/dark/panel_right.png') },
    card: { tl: require('../../assets/ui/panels/dark/card_tl.png'), tr: require('../../assets/ui/panels/dark/card_tr.png'), bl: require('../../assets/ui/panels/dark/card_bl.png'), br: require('../../assets/ui/panels/dark/card_br.png'), top: require('../../assets/ui/panels/dark/card_top.png'), bottom: require('../../assets/ui/panels/dark/card_bottom.png'), left: require('../../assets/ui/panels/dark/card_left.png'), right: require('../../assets/ui/panels/dark/card_right.png') },
    buttons: {
      primary: { md: { up: { l: require('../../assets/ui/panels/dark/btn_primary_md_up_l.png'), m: require('../../assets/ui/panels/dark/btn_primary_md_up_m.png'), r: require('../../assets/ui/panels/dark/btn_primary_md_up_r.png') }, down: { l: require('../../assets/ui/panels/dark/btn_primary_md_down_l.png'), m: require('../../assets/ui/panels/dark/btn_primary_md_down_m.png'), r: require('../../assets/ui/panels/dark/btn_primary_md_down_r.png') } }, lg: { up: { l: require('../../assets/ui/panels/dark/btn_primary_lg_up_l.png'), m: require('../../assets/ui/panels/dark/btn_primary_lg_up_m.png'), r: require('../../assets/ui/panels/dark/btn_primary_lg_up_r.png') }, down: { l: require('../../assets/ui/panels/dark/btn_primary_lg_down_l.png'), m: require('../../assets/ui/panels/dark/btn_primary_lg_down_m.png'), r: require('../../assets/ui/panels/dark/btn_primary_lg_down_r.png') } } },
      secondary: { md: { up: { l: require('../../assets/ui/panels/dark/btn_secondary_md_up_l.png'), m: require('../../assets/ui/panels/dark/btn_secondary_md_up_m.png'), r: require('../../assets/ui/panels/dark/btn_secondary_md_up_r.png') }, down: { l: require('../../assets/ui/panels/dark/btn_secondary_md_down_l.png'), m: require('../../assets/ui/panels/dark/btn_secondary_md_down_m.png'), r: require('../../assets/ui/panels/dark/btn_secondary_md_down_r.png') } }, lg: { up: { l: require('../../assets/ui/panels/dark/btn_secondary_lg_up_l.png'), m: require('../../assets/ui/panels/dark/btn_secondary_lg_up_m.png'), r: require('../../assets/ui/panels/dark/btn_secondary_lg_up_r.png') }, down: { l: require('../../assets/ui/panels/dark/btn_secondary_lg_down_l.png'), m: require('../../assets/ui/panels/dark/btn_secondary_lg_down_m.png'), r: require('../../assets/ui/panels/dark/btn_secondary_lg_down_r.png') } } },
      quiet: { md: { up: { l: require('../../assets/ui/panels/dark/btn_quiet_md_up_l.png'), m: require('../../assets/ui/panels/dark/btn_quiet_md_up_m.png'), r: require('../../assets/ui/panels/dark/btn_quiet_md_up_r.png') }, down: { l: require('../../assets/ui/panels/dark/btn_quiet_md_down_l.png'), m: require('../../assets/ui/panels/dark/btn_quiet_md_down_m.png'), r: require('../../assets/ui/panels/dark/btn_quiet_md_down_r.png') } }, lg: { up: { l: require('../../assets/ui/panels/dark/btn_quiet_lg_up_l.png'), m: require('../../assets/ui/panels/dark/btn_quiet_lg_up_m.png'), r: require('../../assets/ui/panels/dark/btn_quiet_lg_up_r.png') }, down: { l: require('../../assets/ui/panels/dark/btn_quiet_lg_down_l.png'), m: require('../../assets/ui/panels/dark/btn_quiet_lg_down_m.png'), r: require('../../assets/ui/panels/dark/btn_quiet_lg_down_r.png') } } },
    },
    plaque: { l: require('../../assets/ui/panels/dark/plaque_l.png'), m: require('../../assets/ui/panels/dark/plaque_m.png'), r: require('../../assets/ui/panels/dark/plaque_r.png') },
    fill: '#352A31',
    fillCard: '#2E2429',
    accent: '#9E3B2A',
    accentLo: '#77281C',
    ink: { primary: '#F5E3CB', secondary: '#E8D5B7', quiet: '#BBA68E', plaque: '#CE8654' },
  },
  serene: {
    panel: { tl: require('../../assets/ui/panels/serene/panel_tl.png'), tr: require('../../assets/ui/panels/serene/panel_tr.png'), bl: require('../../assets/ui/panels/serene/panel_bl.png'), br: require('../../assets/ui/panels/serene/panel_br.png'), top: require('../../assets/ui/panels/serene/panel_top.png'), bottom: require('../../assets/ui/panels/serene/panel_bottom.png'), left: require('../../assets/ui/panels/serene/panel_left.png'), right: require('../../assets/ui/panels/serene/panel_right.png') },
    card: { tl: require('../../assets/ui/panels/serene/card_tl.png'), tr: require('../../assets/ui/panels/serene/card_tr.png'), bl: require('../../assets/ui/panels/serene/card_bl.png'), br: require('../../assets/ui/panels/serene/card_br.png'), top: require('../../assets/ui/panels/serene/card_top.png'), bottom: require('../../assets/ui/panels/serene/card_bottom.png'), left: require('../../assets/ui/panels/serene/card_left.png'), right: require('../../assets/ui/panels/serene/card_right.png') },
    buttons: {
      primary: { md: { up: { l: require('../../assets/ui/panels/serene/btn_primary_md_up_l.png'), m: require('../../assets/ui/panels/serene/btn_primary_md_up_m.png'), r: require('../../assets/ui/panels/serene/btn_primary_md_up_r.png') }, down: { l: require('../../assets/ui/panels/serene/btn_primary_md_down_l.png'), m: require('../../assets/ui/panels/serene/btn_primary_md_down_m.png'), r: require('../../assets/ui/panels/serene/btn_primary_md_down_r.png') } }, lg: { up: { l: require('../../assets/ui/panels/serene/btn_primary_lg_up_l.png'), m: require('../../assets/ui/panels/serene/btn_primary_lg_up_m.png'), r: require('../../assets/ui/panels/serene/btn_primary_lg_up_r.png') }, down: { l: require('../../assets/ui/panels/serene/btn_primary_lg_down_l.png'), m: require('../../assets/ui/panels/serene/btn_primary_lg_down_m.png'), r: require('../../assets/ui/panels/serene/btn_primary_lg_down_r.png') } } },
      secondary: { md: { up: { l: require('../../assets/ui/panels/serene/btn_secondary_md_up_l.png'), m: require('../../assets/ui/panels/serene/btn_secondary_md_up_m.png'), r: require('../../assets/ui/panels/serene/btn_secondary_md_up_r.png') }, down: { l: require('../../assets/ui/panels/serene/btn_secondary_md_down_l.png'), m: require('../../assets/ui/panels/serene/btn_secondary_md_down_m.png'), r: require('../../assets/ui/panels/serene/btn_secondary_md_down_r.png') } }, lg: { up: { l: require('../../assets/ui/panels/serene/btn_secondary_lg_up_l.png'), m: require('../../assets/ui/panels/serene/btn_secondary_lg_up_m.png'), r: require('../../assets/ui/panels/serene/btn_secondary_lg_up_r.png') }, down: { l: require('../../assets/ui/panels/serene/btn_secondary_lg_down_l.png'), m: require('../../assets/ui/panels/serene/btn_secondary_lg_down_m.png'), r: require('../../assets/ui/panels/serene/btn_secondary_lg_down_r.png') } } },
      quiet: { md: { up: { l: require('../../assets/ui/panels/serene/btn_quiet_md_up_l.png'), m: require('../../assets/ui/panels/serene/btn_quiet_md_up_m.png'), r: require('../../assets/ui/panels/serene/btn_quiet_md_up_r.png') }, down: { l: require('../../assets/ui/panels/serene/btn_quiet_md_down_l.png'), m: require('../../assets/ui/panels/serene/btn_quiet_md_down_m.png'), r: require('../../assets/ui/panels/serene/btn_quiet_md_down_r.png') } }, lg: { up: { l: require('../../assets/ui/panels/serene/btn_quiet_lg_up_l.png'), m: require('../../assets/ui/panels/serene/btn_quiet_lg_up_m.png'), r: require('../../assets/ui/panels/serene/btn_quiet_lg_up_r.png') }, down: { l: require('../../assets/ui/panels/serene/btn_quiet_lg_down_l.png'), m: require('../../assets/ui/panels/serene/btn_quiet_lg_down_m.png'), r: require('../../assets/ui/panels/serene/btn_quiet_lg_down_r.png') } } },
    },
    plaque: { l: require('../../assets/ui/panels/serene/plaque_l.png'), m: require('../../assets/ui/panels/serene/plaque_m.png'), r: require('../../assets/ui/panels/serene/plaque_r.png') },
    fill: '#332A38',
    fillCard: '#2C2431',
    accent: '#8A6E96',
    accentLo: '#6B5277',
    ink: { primary: '#1F1512', secondary: '#D9C8D4', quiet: '#A793A6', plaque: '#A95341' },
  },
};

/**
 * Skin for a narrative phase. hostDark runs the dialogue-hosted surfaces
 * one material ahead of the world: pre-dark phases map onto storm, and
 * phase 3 (the night sky) maps onto the dark ash material so the most-seen
 * home surface visibly turns when the world does (phase 4 pairings reused,
 * so no new ink/fill contrast pairs are introduced).
 */
export function getPixelSkin(phase: number, hostDark = false): PixelSkin {
  const p = hostDark ? (phase < 3 ? 3 : phase === 3 ? 4 : phase) : phase;
  if (p >= 5) return PIXEL_SKINS.serene;
  if (p >= 4) return PIXEL_SKINS.dark;
  if (p >= 3) return PIXEL_SKINS.storm;
  if (p >= 2) return PIXEL_SKINS.dusk;
  return PIXEL_SKINS.bright;
}
