// Generated by audio/measure.mjs from assets/music/home_phase0.mp3. Do not edit by hand.
export const GRID = {
  "source": "assets/music/home_phase0.mp3",
  "bpm": 136.1,
  "beat": 0.44085,
  "bar": 1.76341,
  "t0Bar1": 1,
  "offset": 98.1864,
  "dropBeatError": 0.016,
  "anchorsFile": {
    "stopIn": 104.56,
    "drop": 106.24,
    "grooveIn": 107.425,
    "breakIn": 120.62,
    "breakOut": 122.115,
    "breath": 129.37,
    "hit": 132.115,
    "preHit": 134.775,
    "finalHit": 135.24
  },
  "anchors": {
    "stopIn": 6.374,
    "drop": 8.054,
    "grooveIn": 9.239,
    "breakIn": 22.434,
    "breakOut": 23.929,
    "breath": 31.184,
    "hit": 33.929,
    "preHit": 36.589,
    "finalHit": 37.054
  },
  "edgeDb": {
    "stopIn": 13,
    "drop": 56.5,
    "grooveIn": 44.7,
    "breakIn": 12.8,
    "breakOut": 62.7,
    "breath": 14.3,
    "hit": 54,
    "preHit": 29.1,
    "finalHit": 34.8
  }
};
