/** Generated by scripts/tools/updateDailyBoardVersion.mjs; checked in CI.
 * Bank content, vocabulary or daily selection changes receive a new cohort.
 */
export const DAILY_BOARD_VERSION = 'daily_v2_b18ea5e220d9fa7b';
/** Saved boards keep their recorded cohort, including the original legacy one. */
export const LEGACY_DAILY_BOARD_VERSION = 'legacy_v1';
