// Measure the music bed so the picture can be cut to it.
//
//   node scripts/store/cinematic/audio/measure.mjs
//
// The trailer plays ONE continuous excerpt of assets/music/home_phase0.mp3.
// This finds its beat grid (136 BPM) and the structural anchors the edit is
// built on (the stop, the drop, the break, the breath and the outro hits),
// then writes src/grid.data.js, which both the picture (src/grid.js) and the
// score (audio/score.mjs) import. If a re-encode moves a hit by a few
// milliseconds, the picture follows automatically.

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const MOBILE = path.resolve(HERE, '../../../..');
const FILE = path.join(MOBILE, 'assets/music/home_phase0.mp3');
const FFMPEG = process.env.FFMPEG || 'ffmpeg';
const SR = 22050;

const raw = execFileSync(FFMPEG, ['-hide_banner', '-loglevel', 'error', '-i', FILE, '-ac', '1', '-ar', String(SR), '-f', 'f32le', '-'], { maxBuffer: 1 << 30 });
const x = new Float32Array(raw.buffer, raw.byteOffset, raw.length / 4);

function lowpass(sig, fc) {
  const w0 = 2 * Math.PI * fc / SR, c = Math.cos(w0), a = Math.sin(w0) / (2 * 0.707);
  const b0 = (1 - c) / 2, b1 = 1 - c, b2 = (1 - c) / 2, a0 = 1 + a, a1 = -2 * c, a2 = 1 - a;
  let x1 = 0, x2 = 0, y1 = 0, y2 = 0; const y = new Float32Array(sig.length);
  for (let i = 0; i < sig.length; i++) { const v = (b0 * sig[i] + b1 * x1 + b2 * x2 - a1 * y1 - a2 * y2) / a0; x2 = x1; x1 = sig[i]; y2 = y1; y1 = v; y[i] = v; }
  return y;
}
const low = lowpass(lowpass(x, 130), 130);
const rmsDb = (sig, t0, t1) => { let e = 0, n = 0; for (let i = Math.max(0, Math.floor(t0 * SR)); i < Math.min(sig.length, t1 * SR); i++) { e += sig[i] * sig[i]; n++; } return 10 * Math.log10(e / Math.max(1, n) + 1e-12); };

/** Time of the steepest rise (dir=+1) or fall (dir=-1) of a band's 30 ms energy within [a, b]. */
function edge(sig, a, b, dir = 1) {
  let best = -1e9, bt = a;
  for (let t = a; t < b; t += 0.005) {
    const d = (rmsDb(sig, t, t + 0.03) - rmsDb(sig, t - 0.06, t - 0.03)) * dir;
    if (d > best) { best = d; bt = t; }
  }
  return { t: +bt.toFixed(3), db: +best.toFixed(1) };
}

// --- beat grid: spectral-flux onsets, then a phase-locked 136 BPM comb fit over the excerpt
function onsetEnvelope(a, b, hop = 0.005) {
  const env = [];
  let prev = rmsDb(x, a - hop, a);
  for (let t = a; t < b; t += hop) { const v = rmsDb(x, t, t + 0.02); env.push(Math.max(0, v - prev)); prev = v; }
  return env;
}
const A = 99.0, B = 136.0, HOP = 0.005;
const env = onsetEnvelope(A, B, HOP);
let bestBpm = 136, bestPhase = 0, bestScore = -1;
for (let bpm = 134; bpm <= 138; bpm += 0.02) {
  const period = 60 / bpm;
  for (let ph = 0; ph < period; ph += 0.005) {
    let s = 0;
    for (let t = ph; t < B - A; t += period) { const i = Math.round(t / HOP); s += (env[i] || 0) + 0.5 * ((env[i - 1] || 0) + (env[i + 1] || 0)); }
    if (s > bestScore) { bestScore = s; bestBpm = bpm; bestPhase = ph; }
  }
}
const beat = 60 / bestBpm;

// --- anchors (search windows around the nominal times measured during design)
const anchors = {
  stopIn: edge(low, 104.5, 105.1, -1),
  drop: edge(low, 106.05, 106.45, 1),
  grooveIn: edge(low, 107.2, 107.6, 1),
  breakIn: edge(low, 120.55, 120.95, -1),
  breakOut: edge(low, 121.9, 122.3, 1),
  breath: edge(low, 129.2, 129.7, -1),
  hit: edge(low, 131.9, 132.3, 1),
  preHit: edge(low, 134.6, 134.86, 1),
  finalHit: edge(low, 135.0, 135.4, 1),
};

// --- placement: the drop lands on bar 5 of the trailer; bar 1 starts at T = 1.000
const BAR = beat * 4;
const T_BAR1 = 1.0;
const offset = anchors.drop.t - (T_BAR1 + 4 * BAR); // T = file - offset
const toT = (f) => +(f - offset).toFixed(3);
const grid = {
  source: 'assets/music/home_phase0.mp3',
  bpm: +bestBpm.toFixed(2),
  beat: +beat.toFixed(5),
  bar: +BAR.toFixed(5),
  t0Bar1: T_BAR1,
  offset: +offset.toFixed(4),
  // phase check: distance (s) of the drop from the nearest fitted beat
  dropBeatError: +(((anchors.drop.t - (A + bestPhase)) / beat - Math.round((anchors.drop.t - (A + bestPhase)) / beat)) * beat).toFixed(3),
  anchorsFile: Object.fromEntries(Object.entries(anchors).map(([k, v]) => [k, v.t])),
  anchors: Object.fromEntries(Object.entries(anchors).map(([k, v]) => [k, toT(v.t)])),
  edgeDb: Object.fromEntries(Object.entries(anchors).map(([k, v]) => [k, v.db])),
};

const out = path.join(HERE, '..', 'src', 'grid.data.js');
fs.writeFileSync(out, `// Generated by audio/measure.mjs from ${grid.source}. Do not edit by hand.\nexport const GRID = ${JSON.stringify(grid, null, 2)};\n`);
console.log(JSON.stringify(grid, null, 1));
console.log('wrote', out);
