/** Generated by scripts/story/buildArtCatalog.mjs; exact lines also resolve older frozen saves. */
export const STORY_ART_CATALOG = [
  {
    "id": "cup-01",
    "scenes": [
      "cup"
    ],
    "samples": [
      "I've got two cups and one important question. Tea, or the terrible cocoa I keep trying to improve?"
    ]
  },
  {
    "id": "cup-02",
    "scenes": [
      "cup"
    ],
    "samples": [
      "One cup has a chip in the handle. The other has a crooked flower painted on it."
    ]
  },
  {
    "id": "cup-03",
    "scenes": [
      "cup"
    ],
    "samples": [
      "That flower was meant to be a fox. You can be kind about it, but please don't lie."
    ]
  },
  {
    "id": "cup-04",
    "scenes": [
      "cup"
    ],
    "samples": [
      "Brave. I mean about the cocoa. The flower is excellent company."
    ]
  },
  {
    "id": "cup-05",
    "scenes": [
      "cup"
    ],
    "samples": [
      "She moves the chipped cup to her own place."
    ]
  },
  {
    "id": "cup-06",
    "scenes": [
      "cup"
    ],
    "samples": [
      "It suits your hand, doesn't it? I keep forgetting that a thing can be chipped and still be exactly right."
    ]
  },
  {
    "id": "cup-07",
    "scenes": [
      "cup"
    ],
    "samples": [
      "She puts the cocoa away and does not look disappointed."
    ]
  },
  {
    "id": "echo-01",
    "scenes": [
      "echo"
    ],
    "samples": [
      "Below the house, HOME catches against the rim instead of sinking."
    ]
  },
  {
    "id": "echo-02",
    "scenes": [
      "echo"
    ],
    "samples": [
      "Wait. I wrote that word in my notebook this morning. Before you brought it down here."
    ]
  },
  {
    "id": "echo-03",
    "scenes": [
      "echo"
    ],
    "samples": [
      "He lays the open notebook down beside the rim. The letters match."
    ]
  },
  {
    "id": "echo-04",
    "scenes": [
      "echo"
    ],
    "samples": [
      "The same letters are already scratched into the stone beside the rim. The scratches are old."
    ]
  },
  {
    "id": "echo-05",
    "scenes": [
      "echo"
    ],
    "samples": [
      "I could call this a coincidence, friend. I would like that word to be some help. It is not.",
      "I could call this a coincidence, friend. I'd like to. It doesn't explain a thing."
    ]
  },
  {
    "id": "echo-06",
    "scenes": [
      "echo"
    ],
    "samples": [
      "The word sinks. Its reflection stays on the surface one moment longer."
    ]
  },
  {
    "id": "witness-01",
    "scenes": [
      "witness"
    ],
    "samples": [
      "You write down what happened by the rim: the same word, already there before you offered it. You put the date beneath it."
    ]
  },
  {
    "id": "witness-02",
    "scenes": [
      "witness"
    ],
    "samples": [
      "I would like to fold that page away, friend. I can hear myself reaching for another comforting explanation."
    ]
  },
  {
    "id": "witness-03",
    "scenes": [
      "witness"
    ],
    "samples": [
      "But you were there too. Shall we tell the household what we saw, or keep the account between us while we look into it?",
      "But you were there too. Do we tell the household what we saw, or keep the account between us while we look into it?"
    ]
  },
  {
    "id": "witness-04",
    "scenes": [
      "witness"
    ],
    "samples": [
      "You bring the account to the shared table. Those who read it add their initials beneath the date."
    ]
  },
  {
    "id": "witness-05",
    "scenes": [
      "witness"
    ],
    "samples": [
      "I will tell them what happened. I will say I do not know why. You can stop me if I start making it sound safer than it is."
    ]
  },
  {
    "id": "witness-06",
    "scenes": [
      "witness"
    ],
    "samples": [
      "You fold the dated account and keep it with you. Ember leaves the outside blank."
    ]
  },
  {
    "id": "witness-07",
    "scenes": [
      "witness"
    ],
    "samples": [
      "Between us, then. When you want someone else to read it, you can be the one to open it."
    ]
  },
  {
    "id": "supper-01",
    "scenes": [
      "supper"
    ],
    "samples": [
      "Ember sets your flower cup at your place. She has been working on the cocoa recipe again.",
      "Ember sets your chipped cup at your place. She remembered that you asked for tea."
    ]
  },
  {
    "id": "supper-02",
    "scenes": [
      "supper"
    ],
    "samples": [
      "Supper. Now. The empty place at the table can wait. The rest of us have stomachs."
    ]
  },
  {
    "id": "supper-03",
    "scenes": [
      "supper"
    ],
    "samples": [
      "She sets the covered dish aside on the floor and serves everyone from the ordinary pot."
    ]
  },
  {
    "id": "supper-04",
    "scenes": [
      "supper"
    ],
    "samples": [
      "I spent the whole afternoon keeping a place warm for someone who has not come. Your drink went cold while I did it. That is ridiculous of me, friend."
    ]
  },
  {
    "id": "supper-05",
    "scenes": [
      "supper"
    ],
    "samples": [
      "The empty cup is moved aside. Fresh tea goes in yours.",
      "The empty cup is moved aside. Fresh tea goes in your chipped cup.",
      "The empty cup is moved aside. Fresh cocoa goes in your flower cup."
    ]
  },
  {
    "id": "supper-06",
    "scenes": [
      "supper"
    ],
    "samples": [
      "Is it safe?"
    ]
  },
  {
    "id": "supper-07",
    "scenes": [
      "supper"
    ],
    "samples": [
      "It is soup. I made it myself. Ask me about the house after you have eaten."
    ]
  },
  {
    "id": "supper-08",
    "scenes": [
      "supper"
    ],
    "samples": [
      "The tea is safe. I cannot promise you anything else tonight."
    ]
  },
  {
    "id": "supper-09",
    "scenes": [
      "supper"
    ],
    "samples": [
      "For a while the room sounds like an ordinary supper, not like a room listening for something."
    ]
  },
  {
    "id": "supper-10",
    "scenes": [
      "supper"
    ],
    "samples": [
      "The dated account lies between the dishes, its row of initials visible."
    ]
  },
  {
    "id": "supper-11",
    "scenes": [
      "supper"
    ],
    "samples": [
      "You asked us to tell everyone. If anyone has seen something else, this is a good place to say it."
    ]
  },
  {
    "id": "supper-12",
    "scenes": [
      "supper"
    ],
    "samples": [
      "The folded account is still in your pocket. Ember glances toward you, then leaves it for you to bring up."
    ]
  },
  {
    "id": "supper-13",
    "scenes": [
      "supper"
    ],
    "samples": [
      "Under the table, the low hum below the floor slips out of rhythm. Nobody hurries to set it right."
    ]
  },
  {
    "id": "plan-01",
    "scenes": [
      "plan"
    ],
    "samples": [
      "I always read this line on the old plan as a brace. Look which way it points."
    ]
  },
  {
    "id": "plan-02",
    "scenes": [
      "plan"
    ],
    "samples": [
      "Warren turns a drawing of the foundations so the doorway faces you."
    ]
  },
  {
    "id": "plan-03",
    "scenes": [
      "plan"
    ],
    "samples": [
      "A loose plan lies under the oldest hearthstone. Its arrows point in toward the house, not away from it."
    ]
  },
  {
    "id": "plan-04",
    "scenes": [
      "plan"
    ],
    "samples": [
      "My watch keeps the house in sight all night. Nobody ever told me who I am watching for."
    ]
  },
  {
    "id": "plan-05",
    "scenes": [
      "plan"
    ],
    "samples": [
      "All that work to keep something out. Or maybe, friend, that is only what we wanted the drawing to mean."
    ]
  },
  {
    "id": "plan-06",
    "scenes": [
      "plan"
    ],
    "samples": [
      "I wrote \"defense\" beside this mark in the old book. The book never used that word. I did."
    ]
  },
  {
    "id": "plan-07",
    "scenes": [
      "plan"
    ],
    "samples": [
      "Someone has written SAFE in the margin. The handwriting is much newer than the plan."
    ]
  },
  {
    "id": "plan-08",
    "scenes": [
      "plan"
    ],
    "samples": [
      "A line goes through the reassuring word. Nobody writes a new one under it. It is the first answer anyone has crossed out."
    ]
  },
  {
    "id": "shelter-01",
    "scenes": [
      "shelter"
    ],
    "samples": [
      "The arrows on the old plan all point inward. Beside the drawing, you set a lamp and a small latch."
    ]
  },
  {
    "id": "shelter-02",
    "scenes": [
      "shelter"
    ],
    "samples": [
      "I can mark the road beyond the gate. Or fit this latch to a door we already have, and ask everyone to knock. Which shall I start with?"
    ]
  },
  {
    "id": "shelter-03",
    "scenes": [
      "shelter"
    ],
    "samples": [
      "We could mark the road beyond the gate, friend. Or put this latch on a door we already have, and ask everyone to knock. Which would help you tonight?"
    ]
  },
  {
    "id": "shelter-04",
    "scenes": [
      "shelter"
    ],
    "samples": [
      "Neither a lamp nor a latch can promise to stop what is below the house. They are things the people here can do for one another now."
    ]
  },
  {
    "id": "shelter-05",
    "scenes": [
      "shelter"
    ],
    "samples": [
      "You set the lamp by the gate. Together, you place pale stones along the outward path, as far as the trees."
    ]
  },
  {
    "id": "shelter-06",
    "scenes": [
      "shelter"
    ],
    "samples": [
      "I will keep these markers clear. I cannot tell you yet what happens past the trees."
    ]
  },
  {
    "id": "shelter-07",
    "scenes": [
      "shelter"
    ],
    "samples": [
      "I will keep the lamp filled. I wish that were the same as knowing where the road ends. It is a start."
    ]
  },
  {
    "id": "shelter-08",
    "scenes": [
      "shelter"
    ],
    "samples": [
      "The latch is fitted to the inside of an existing door. You hang a small sign on the outside: PLEASE KNOCK."
    ]
  },
  {
    "id": "shelter-09",
    "scenes": [
      "shelter"
    ],
    "samples": [
      "No new room, no clever seal. Just a door that stays shut until you open it. I can ask people to respect that."
    ]
  },
  {
    "id": "shelter-10",
    "scenes": [
      "shelter"
    ],
    "samples": [
      "I can promise to knock, friend. Whatever the house does, I can wait until you ask me in."
    ]
  },
  {
    "id": "plum-01",
    "scenes": [
      "plum",
      "plum_recruited"
    ],
    "samples": [
      "This is PLUM! He is on his first lap of the tank, worried face and all. He usually stops swimming when I laugh."
    ]
  },
  {
    "id": "plum-02",
    "scenes": [
      "plum",
      "plum_recruited"
    ],
    "samples": [
      "Axel blows a crooked bubble. PLUM noses it, then turns back to him."
    ]
  },
  {
    "id": "plum-03",
    "scenes": [
      "plum",
      "plum_recruited"
    ],
    "samples": [
      "He is old for a fish. I keep forgetting how quickly somebody else can get old."
    ]
  },
  {
    "id": "plum-04",
    "scenes": [
      "plum",
      "plum_recruited"
    ],
    "samples": [
      "His small hand follows PLUM along the glass, close but never touching."
    ]
  },
  {
    "id": "plum-05",
    "scenes": [
      "plum",
      "plum_recruited"
    ],
    "samples": [
      "You hold your flower cup. The cocoa is warm against your hands.",
      "You hold your chipped cup. The tea is warm against your hands."
    ]
  },
  {
    "id": "plum-06",
    "scenes": [
      "plum",
      "plum_recruited"
    ],
    "samples": [
      "This cup has a chip in it, friend, from the day I dropped it. I still remember who was sitting with me. It would be a poorer cup without that chip."
    ]
  },
  {
    "id": "plum-07",
    "scenes": [
      "plum",
      "plum_recruited"
    ],
    "samples": [
      "Below the house, a word comes back up out of the dark exactly as it went down. Its reflection does not waver at all."
    ]
  },
  {
    "id": "plum-08",
    "scenes": [
      "plum",
      "plum_recruited"
    ],
    "samples": [
      "Whatever is down there keeps the shape of everything, exactly. I am starting to wonder whether keeping the shape is enough."
    ]
  },
  {
    "id": "record-01",
    "scenes": [
      "record"
    ],
    "samples": [
      "I wrote this in the ledger: \"I am afraid.\" Three words, complete and accurate."
    ]
  },
  {
    "id": "record-02",
    "scenes": [
      "record"
    ],
    "samples": [
      "On his ledger, the ink now reads: EVERYTHING IS WELL."
    ]
  },
  {
    "id": "record-03",
    "scenes": [
      "record"
    ],
    "samples": [
      "That is tidier. It is also not what I wrote."
    ]
  },
  {
    "id": "record-04",
    "scenes": [
      "record"
    ],
    "samples": [
      "On a page beside the hearth, I AM AFRAID changes to EVERYTHING IS WELL. The wet ink shines."
    ]
  },
  {
    "id": "record-05",
    "scenes": [
      "record"
    ],
    "samples": [
      "I watched those letters move with no hand near them. Whatever moved them meant to help, friend. That is what makes this hard."
    ]
  },
  {
    "id": "record-06",
    "scenes": [
      "record"
    ],
    "samples": [
      "We will bring this to the shared table, beside the dated account. You asked us to compare what we saw. We need to keep doing that."
    ]
  },
  {
    "id": "record-07",
    "scenes": [
      "record"
    ],
    "samples": [
      "You unfold the dated account beside the ledger. For now, you and Ember compare the pages in private."
    ]
  },
  {
    "id": "record-08",
    "scenes": [
      "record"
    ],
    "samples": [
      "Keeping the paper is one thing. Remembering what was on it is another. I will remember with you."
    ]
  },
  {
    "id": "record-09",
    "scenes": [
      "record"
    ],
    "samples": [
      "I have ink."
    ]
  },
  {
    "id": "record-10",
    "scenes": [
      "record"
    ],
    "samples": [
      "Then we will need another pen."
    ]
  },
  {
    "id": "record-11",
    "scenes": [
      "record"
    ],
    "samples": [
      "The original sentence is copied onto a loose page and kept away from the ledger."
    ]
  },
  {
    "id": "record-12",
    "scenes": [
      "record"
    ],
    "samples": [
      "I can leave the house's version on the page. I will not put my name to it."
    ]
  },
  {
    "id": "record-13",
    "scenes": [
      "record"
    ],
    "samples": [
      "We can leave the page alone. We do not have to believe what it says."
    ]
  },
  {
    "id": "record-14",
    "scenes": [
      "record"
    ],
    "samples": [
      "You remember both sentences. The house kept only one."
    ]
  },
  {
    "id": "seeds-01",
    "scenes": [
      "seeds"
    ],
    "samples": [
      "I packed seeds. I have not decided to leave. I packed them so that leaving stays something I can still choose."
    ]
  },
  {
    "id": "seeds-02",
    "scenes": [
      "seeds"
    ],
    "samples": [
      "Thyme sets a small tin down beside the garden gate."
    ]
  },
  {
    "id": "seeds-03",
    "scenes": [
      "seeds"
    ],
    "samples": [
      "Will you keep this between us, or help me tell Ember? I can live with either answer. I cannot live with everyone deciding for me again."
    ]
  },
  {
    "id": "seeds-04",
    "scenes": [
      "seeds"
    ],
    "samples": [
      "I used to tell you that you could always leave. I have never walked that road past the trees myself."
    ]
  },
  {
    "id": "seeds-05",
    "scenes": [
      "seeds"
    ],
    "samples": [
      "By the gate, you set a small stone on the path that leads away. A mark you can come back and check."
    ]
  },
  {
    "id": "seeds-06",
    "scenes": [
      "seeds"
    ],
    "samples": [
      "I saw the lamp you put here, and the pale stones. Someone had thought about leaving before I packed. That helped."
    ]
  },
  {
    "id": "seeds-07",
    "scenes": [
      "seeds"
    ],
    "samples": [
      "The lamp you chose is still filled. You clear fallen leaves from the pale stones along the outward path."
    ]
  },
  {
    "id": "seeds-08",
    "scenes": [
      "seeds"
    ],
    "samples": [
      "People really wait at that PLEASE KNOCK sign you put up. I want that same say over this tin."
    ]
  },
  {
    "id": "seeds-09",
    "scenes": [
      "seeds"
    ],
    "samples": [
      "I have learned to wait at your PLEASE KNOCK sign. I want the gate to mean something you can decide, too."
    ]
  },
  {
    "id": "seeds-10",
    "scenes": [
      "seeds"
    ],
    "samples": [
      "Thank you. A secret is a little room with its own door, and I am the one who opens it."
    ]
  },
  {
    "id": "seeds-11",
    "scenes": [
      "seeds"
    ],
    "samples": [
      "Then the stone at the gate stays between us. I will not speak for you."
    ]
  },
  {
    "id": "seeds-12",
    "scenes": [
      "seeds"
    ],
    "samples": [
      "I will help. And I will ask you first before I tell anyone else."
    ]
  },
  {
    "id": "seeds-13",
    "scenes": [
      "seeds"
    ],
    "samples": [
      "Asking first. That would have been a good rule from the very beginning."
    ]
  },
  {
    "id": "seeds-14",
    "scenes": [
      "seeds"
    ],
    "samples": [
      "The stone stays on the outward side of the gate, pointing away from the house."
    ]
  },
  {
    "id": "promise-01",
    "scenes": [
      "promise"
    ],
    "samples": [
      "I told you I was keeping you safe. That was the promise."
    ]
  },
  {
    "id": "promise-02",
    "scenes": [
      "promise"
    ],
    "samples": [
      "Did you know what the words were for?"
    ]
  },
  {
    "id": "promise-03",
    "scenes": [
      "promise"
    ],
    "samples": [
      "I knew enough to tell you. And I did not tell you."
    ]
  },
  {
    "id": "promise-04",
    "scenes": [
      "promise"
    ],
    "samples": [
      "I knew I was inviting something in. I thought a house full of people who loved each other would teach it to be gentle."
    ]
  },
  {
    "id": "promise-05",
    "scenes": [
      "promise"
    ],
    "samples": [
      "I wanted it to come. I called my waiting patience. That word made it easier to watch everyone else wait without knowing why."
    ]
  },
  {
    "id": "promise-06",
    "scenes": [
      "promise"
    ],
    "samples": [
      "The love in this house was real, friend. It does not excuse what I kept from you."
    ]
  },
  {
    "id": "promise-07",
    "scenes": [
      "promise"
    ],
    "samples": [
      "Through the window, the lamp you chose is lit by the gate."
    ]
  },
  {
    "id": "promise-08",
    "scenes": [
      "promise"
    ],
    "samples": [
      "I filled that lamp again. Doing the thing you asked does not make up for the thing I kept from you."
    ]
  },
  {
    "id": "promise-09",
    "scenes": [
      "promise"
    ],
    "samples": [
      "The conversation began with a knock. Ember waited until you opened the latched door."
    ]
  },
  {
    "id": "promise-10",
    "scenes": [
      "promise"
    ],
    "samples": [
      "You asked us to wait for permission. I should have understood that before we put up the sign.",
      "You asked us to wait until we were let in. I should have kept that rule long before anyone had to write it on a sign."
    ]
  },
  {
    "id": "promise-11",
    "scenes": [
      "promise"
    ],
    "samples": [
      "I will tell you the rest. And when I do not know something, I will say so."
    ]
  },
  {
    "id": "promise-12",
    "scenes": [
      "promise"
    ],
    "samples": [
      "All right. I will keep my distance. Your place in this house does not depend on forgiving me."
    ]
  },
  {
    "id": "promise-13",
    "scenes": [
      "promise"
    ],
    "samples": [
      "She moves her chair. The cup stays within your reach.",
      "She moves her chair. Your flower cup stays within your reach.",
      "She moves her chair. Your chipped cup stays within your reach."
    ]
  },
  {
    "id": "returned-01",
    "scenes": [
      "returned"
    ],
    "samples": [
      "PLUM died. I let him drift down to the bottom of the tank. I should have told someone before I did that.",
      "PLUM died. I laid him on the gravel and told nobody. I did not want anyone to say something kind yet. This morning the gravel was empty."
    ]
  },
  {
    "id": "returned-02",
    "scenes": [
      "returned"
    ],
    "samples": [
      "Something with PLUM's worried face swims a full circle of the tank. Then it swims the same circle again, exactly."
    ]
  },
  {
    "id": "returned-03",
    "scenes": [
      "returned"
    ],
    "samples": [
      "The same bite out of his fin. The same little face."
    ]
  },
  {
    "id": "returned-04",
    "scenes": [
      "returned"
    ],
    "samples": [
      "Axel laughs once. PLUM always stopped for that. This fish keeps swimming."
    ]
  },
  {
    "id": "returned-05",
    "scenes": [
      "returned"
    ],
    "samples": [
      "Let me have tonight. I am not ready to work this out."
    ]
  },
  {
    "id": "returned-06",
    "scenes": [
      "returned"
    ],
    "samples": [
      "It kept the part of PLUM it could understand, friend. The shape of him. We will have to show it what it left out."
    ]
  },
  {
    "id": "returned-07",
    "scenes": [
      "returned"
    ],
    "samples": [
      "The old cup by the hearth is whole again. Even the line where it was mended has disappeared.",
      "The old chipped cup sits by the hearth. This morning its handle is smooth and whole."
    ]
  },
  {
    "id": "returned-08",
    "scenes": [
      "returned"
    ],
    "samples": [
      "This is the cup I wanted back, friend. And I cannot remember who was sitting with me when I broke it.",
      "Something mended it in the night, friend. I never asked it to."
    ]
  },
  {
    "id": "returned-09",
    "scenes": [
      "returned"
    ],
    "samples": [
      "She turns the cup over in her paws, looking for the chip."
    ]
  },
  {
    "id": "returned-10",
    "scenes": [
      "returned"
    ],
    "samples": [
      "The shape is perfect. The chip is gone, and so is the memory of breaking it.",
      "The shape is perfect. And I cannot remember who was sitting with me the day I dropped it. I used to."
    ]
  },
  {
    "id": "council-01",
    "scenes": [
      "council"
    ],
    "samples": [
      "The work stops. The last arrangement has not been made yet.",
      "The household gathers at the long table. One arrangement is left, and everyone knows it."
    ]
  },
  {
    "id": "council-02",
    "scenes": [
      "council"
    ],
    "samples": [
      "A page that said I AM AFRAID now says EVERYTHING IS WELL. The house calls that kindness: keep the sentence, take away the discomfort."
    ]
  },
  {
    "id": "council-03",
    "scenes": [
      "council"
    ],
    "samples": [
      "It learned how to keep us exactly as we are, friend. It never learned where that has to stop.",
      "What lives under this house learned how to keep us exactly as we are, friend. Nobody ever taught it where to stop."
    ]
  },
  {
    "id": "council-04",
    "scenes": [
      "council"
    ],
    "samples": [
      "I moved my cushion out of the middle of the mat. There are other places to sit. I should have moved it sooner.",
      "I sat at the center, where every stalk points, and called that understanding. I have moved my mat. I was far more certain than I had any right to be."
    ]
  },
  {
    "id": "council-06",
    "scenes": [
      "council"
    ],
    "samples": [
      "The path beyond the gate leads away from the house, and back to it."
    ]
  },
  {
    "id": "council-07",
    "scenes": [
      "council"
    ],
    "samples": [
      "I'll hang a door you can open from either side. You try the latch yourself before I call the job finished."
    ]
  },
  {
    "id": "council-08",
    "scenes": [
      "council"
    ],
    "samples": [
      "Two words will fit at the end, friend. CLOSED keeps one room it cannot enter. A thought you have in there stays yours, uncorrected.",
      "Two words will fit at the end, friend. Either one lets it in to live with us. CLOSED keeps one room it can never enter. A thought you have in there stays yours, uncorrected."
    ]
  },
  {
    "id": "council-09",
    "scenes": [
      "council"
    ],
    "samples": [
      "CLOSER lets it come and live with us, and keeps a road that leads away. Anyone who stays must be able to leave.",
      "CLOSER keeps one road out that it can never close. Anyone who stays must be able to leave."
    ]
  },
  {
    "id": "council-10",
    "scenes": [
      "council"
    ],
    "samples": [
      "The dated account is laid on the table again. The people who put their initials on it are asked what they remember."
    ]
  },
  {
    "id": "council-11",
    "scenes": [
      "council"
    ],
    "samples": [
      "Your folded account stays with you. What the household has learned since does not give anyone permission to open it."
    ]
  },
  {
    "id": "council-12",
    "scenes": [
      "council"
    ],
    "samples": [
      "We marked the road because you asked us to. CLOSER can keep that way out open. You may still choose CLOSED, friend; putting out a lamp did not choose your last word.",
      "We marked the road because you asked. CLOSER would keep that road open for good. You can still choose CLOSED, friend. A lamp by the gate did not choose your last word for you."
    ]
  },
  {
    "id": "council-13",
    "scenes": [
      "council"
    ],
    "samples": [
      "We fitted the latch because you asked us to. CLOSED can make that room private from the presence too. You may still choose CLOSER; fitting a latch did not choose your last word.",
      "We fitted the latch because you asked. CLOSED would shut that room to it as well as to us. You can still choose CLOSER, friend. A latch did not choose your last word for you."
    ]
  },
  {
    "id": "council-14",
    "scenes": [
      "council"
    ],
    "samples": [
      "Both words work. Neither is the greater offering. The last letter you move sets the boundary.",
      "The last arrangement ends at CLOSE. Give it the D, and it reads CLOSED. Give it the R, and it reads CLOSER. Neither is the greater offering."
    ]
  },
  {
    "id": "after-02",
    "scenes": [
      "after"
    ],
    "samples": [
      "Breakfast. I burned one side and saved the other. You may call it a disaster or a rescue, whichever you prefer."
    ]
  },
  {
    "id": "after-03",
    "scenes": [
      "after"
    ],
    "samples": [
      "I made cocoa. There is also toast, if you are willing to scrape it.",
      "I made tea. There is also toast, if you are willing to scrape it."
    ]
  },
  {
    "id": "after-04",
    "scenes": [
      "after"
    ],
    "samples": [
      "A hinge is squeaking. Ordinary squeak, nothing stranger. I've got the right oil for this one."
    ]
  },
  {
    "id": "after-05",
    "scenes": [
      "after"
    ],
    "samples": [
      "I told a funny story about PLUM. Then I felt sad again. Could we have breakfast anyway?"
    ]
  },
  {
    "id": "after-06",
    "scenes": [
      "after"
    ],
    "samples": [
      "An empty chair waits beside the table.",
      "Your chipped cup is at the place you left it.",
      "Your flower cup is at the place you left it."
    ]
  },
  {
    "id": "after-07",
    "scenes": [
      "after"
    ],
    "samples": [
      "The arrival has already happened. In the quiet after it, someone asks what the house has learned."
    ]
  },
  {
    "id": "after-08",
    "scenes": [
      "after"
    ],
    "samples": [
      "The seam in the sky has closed. The presence stayed. Now comes the ordinary work of living together.",
      "The seam in the sky has closed. The presence stayed. This morning, someone tests what your last word actually kept."
    ]
  },
  {
    "id": "after-09",
    "scenes": [
      "after"
    ],
    "samples": [
      "One door stays closed. Behind it, the words I AM AFRAID are exactly as their author left them."
    ]
  },
  {
    "id": "after-10",
    "scenes": [
      "after"
    ],
    "samples": [
      "I filed the original page in that room. Not one letter has been corrected since.",
      "I wrote those words again, inside that room. This time the ink stayed."
    ]
  },
  {
    "id": "after-11",
    "scenes": [
      "after"
    ],
    "samples": [
      "The warmth stopped at that door. I waited a long time to be certain."
    ]
  },
  {
    "id": "after-12",
    "scenes": [
      "after"
    ],
    "samples": [
      "A small stone still sits at the gate, marking the way out. The path runs past the last tree and does not turn back."
    ]
  },
  {
    "id": "after-13",
    "scenes": [
      "after"
    ],
    "samples": [
      "I walked out until I could not see the house. Then I came back. Coming back was my own decision."
    ]
  },
  {
    "id": "after-14",
    "scenes": [
      "after"
    ],
    "samples": [
      "I followed the path past the trees. Coming back felt different, knowing I could have kept walking."
    ]
  },
  {
    "id": "after-15",
    "scenes": [
      "after"
    ],
    "samples": [
      "Someone sets a cup down where the pattern's lines do not run. The house used to put a stray cup back. This one has not moved for a long time.",
      "Someone leaves a cup a little crooked at the edge of the table. The house used to straighten a stray cup by morning. This one is still crooked."
    ]
  },
  {
    "id": "after-16",
    "scenes": [
      "after"
    ],
    "samples": [
      "One small thing left exactly where we put it. I am watching to see whether it stays there."
    ]
  },
  {
    "id": "after-17",
    "scenes": [
      "after"
    ],
    "samples": [
      "I am still not ready to say what I think about the fish. Thank you for not finishing that thought for me."
    ]
  },
  {
    "id": "after-18",
    "scenes": [
      "after"
    ],
    "samples": [
      "You do not owe this morning any particular feeling, friend.",
      "Feel however you feel about this morning, friend. Nobody here gets to correct it."
    ]
  },
  {
    "id": "reply-01",
    "scenes": [
      "reply"
    ],
    "samples": [
      "Your flower cup waits beside the chair you chose. Nobody has moved it.",
      "Your chipped cup waits beside the chair you chose. Nobody has moved it."
    ]
  },
  {
    "id": "reply-02",
    "scenes": [
      "reply"
    ],
    "samples": [
      "We have talked a great deal, friend. I would like to listen now.",
      "I have done most of the talking, friend. It is your turn. I am listening."
    ]
  },
  {
    "id": "reply-03",
    "scenes": [
      "reply"
    ],
    "samples": [
      "Yes. I will not rush you out of that anger. I did not tell you the whole truth when it mattered."
    ]
  },
  {
    "id": "reply-04",
    "scenes": [
      "reply"
    ],
    "samples": [
      "She lets your answer stand. Nothing corrects it."
    ]
  },
  {
    "id": "reply-05",
    "scenes": [
      "reply"
    ],
    "samples": [
      "So do I. This time I am saying it as a wish, not as a promise I cannot keep."
    ]
  },
  {
    "id": "reply-06",
    "scenes": [
      "reply"
    ],
    "samples": [
      "Chairs are pulled up to the table. Nobody arranges them into a circle."
    ]
  },
  {
    "id": "reply-07",
    "scenes": [
      "reply"
    ],
    "samples": [
      "Then that is where we begin. Not knowing is allowed. Nobody gets to finish that sentence for you."
    ]
  },
  {
    "id": "reply-08",
    "scenes": [
      "reply"
    ],
    "samples": [
      "For once the silence is allowed to last. Nobody hurries to fill it."
    ]
  },
  {
    "id": "reply-09",
    "scenes": [
      "reply"
    ],
    "samples": [
      "You left a gap between the chairs. She sits on her side of it. Nobody asks you to call this peace."
    ]
  },
  {
    "id": "old_mark-01",
    "scenes": [
      "old_mark"
    ],
    "samples": [
      "The bright mornings are back. One old mark has survived them."
    ]
  },
  {
    "id": "old_mark-02",
    "scenes": [
      "old_mark"
    ],
    "samples": [
      "One door does not quite match the new walls. Behind it, an old sentence still stands, and nothing has corrected it."
    ]
  },
  {
    "id": "old_mark-03",
    "scenes": [
      "old_mark"
    ],
    "samples": [
      "I don't remember writing that, friend. But I know what it took to leave it there and not fix it.",
      "I don't remember who wrote that, friend. But I know what it took to leave it there and not fix it."
    ]
  },
  {
    "id": "old_mark-04",
    "scenes": [
      "old_mark"
    ],
    "samples": [
      "A small stone at the garden gate points outward. The path past it runs straight away from the house."
    ]
  },
  {
    "id": "old_mark-05",
    "scenes": [
      "old_mark"
    ],
    "samples": [
      "I meant to turn that stone back toward the house. When I got there, I didn't want to."
    ]
  },
  {
    "id": "old_mark-06",
    "scenes": [
      "old_mark"
    ],
    "samples": [
      "Two chairs sit apart, with room between them for a third that nobody has added. Ember measures the gap with her paw and leaves it alone."
    ]
  },
  {
    "id": "old_mark-07",
    "scenes": [
      "old_mark"
    ],
    "samples": [
      "This page is old. The correction over it is newer. Then the original was written back in on top, newer still. Someone kept arguing."
    ]
  },
  {
    "id": "old_mark-08",
    "scenes": [
      "old_mark"
    ],
    "samples": [
      "We chose something once. It has lasted longer than our memory of choosing it."
    ]
  },
  {
    "id": "council-05-road",
    "scenes": [
      "council"
    ],
    "samples": [
      "I want a way out. Even on the days when I choose to stay."
    ]
  },
  {
    "id": "council-15-beside",
    "scenes": [
      "council"
    ],
    "samples": [
      "I will stand beside you, friend. You asked me to."
    ]
  },
  {
    "id": "after-road-release",
    "scenes": [
      "after"
    ],
    "samples": [
      "The pale stones you laid lead to the road your last word kept open. Someone fills the lamp by the gate each evening."
    ]
  },
  {
    "id": "council-15-apart",
    "scenes": [
      "council"
    ],
    "samples": [
      "I will stay by the hearth, friend. You can have as much room as you need."
    ]
  },
  {
    "id": "after-witness-private",
    "scenes": [
      "after"
    ],
    "samples": [
      "You keep the dated account folded. Ember has not opened it for anyone else. When you want to tell that part of the story, you still get to be the one who tells it."
    ]
  },
  {
    "id": "after-room-release",
    "scenes": [
      "after"
    ],
    "samples": [
      "The PLEASE KNOCK sign stays beside the latch you chose. People still wait for an answer. The road, rather than this room, is the boundary that holds against the presence."
    ]
  },
  {
    "id": "after-01-road",
    "scenes": [
      "after"
    ],
    "samples": [
      "Someone walked out through the gate and came back with mud on their feet. Someone else fetches a cloth."
    ]
  },
  {
    "id": "after-road-remember",
    "scenes": [
      "after"
    ],
    "samples": [
      "Someone still fills the lamp by the gate each evening. The pale stones remain where you laid them, though it was a private room you chose to protect."
    ]
  },
  {
    "id": "council-05-private",
    "scenes": [
      "council"
    ],
    "samples": [
      "There is one thing I am keeping to myself. I am not going to say what it is. That should be allowed."
    ]
  },
  {
    "id": "after-room-remember",
    "scenes": [
      "after"
    ],
    "samples": [
      "The PLEASE KNOCK sign still hangs beside the latch you chose. People wait for an answer, and now the warmth must wait outside that room too."
    ]
  },
  {
    "id": "after-witness-share",
    "scenes": [
      "after"
    ],
    "samples": [
      "At the shared table, the dated account has room beneath the initials for anyone to add what they remember. You asked for witnesses; people still come to compare their accounts."
    ]
  },
  {
    "id": "after-01-private",
    "scenes": [
      "after"
    ],
    "samples": [
      "The private door is still closed. In the kitchen, a pan has started smoking."
    ]
  },
  {
    "id": "cup-recollection",
    "scenes": [
      "cup"
    ],
    "samples": [
      "From an earlier evening in the house, a conversation worth keeping."
    ]
  },
  {
    "id": "echo-recollection",
    "scenes": [
      "echo"
    ],
    "samples": [
      "From an earlier evening in the house, a conversation worth keeping."
    ]
  },
  {
    "id": "witness-recollection",
    "scenes": [
      "witness"
    ],
    "samples": [
      "From an earlier evening in the house, a conversation worth keeping."
    ]
  },
  {
    "id": "supper-recollection",
    "scenes": [
      "supper"
    ],
    "samples": [
      "From an earlier evening in the house, a conversation worth keeping."
    ]
  },
  {
    "id": "plan-recollection",
    "scenes": [
      "plan"
    ],
    "samples": [
      "From an earlier evening in the house, a conversation worth keeping."
    ]
  },
  {
    "id": "shelter-recollection",
    "scenes": [
      "shelter"
    ],
    "samples": [
      "From an earlier evening in the house, a conversation worth keeping."
    ]
  },
  {
    "id": "plum-recollection",
    "scenes": [
      "plum"
    ],
    "samples": [
      "From an earlier evening in the house, a conversation worth keeping."
    ]
  },
  {
    "id": "plum_recruited-recollection",
    "scenes": [
      "plum_recruited"
    ],
    "samples": [
      "From an earlier evening in the house, a conversation worth keeping."
    ]
  },
  {
    "id": "record-recollection",
    "scenes": [
      "record"
    ],
    "samples": [
      "From an earlier evening in the house, a conversation worth keeping."
    ]
  },
  {
    "id": "seeds-recollection",
    "scenes": [
      "seeds"
    ],
    "samples": [
      "From an earlier evening in the house, a conversation worth keeping."
    ]
  },
  {
    "id": "promise-recollection",
    "scenes": [
      "promise"
    ],
    "samples": [
      "From an earlier evening in the house, a conversation worth keeping."
    ]
  },
  {
    "id": "returned-recollection",
    "scenes": [
      "returned"
    ],
    "samples": [
      "From an earlier evening in the house, a conversation worth keeping."
    ]
  },
  {
    "id": "council-recollection",
    "scenes": [
      "council"
    ],
    "samples": [
      "From an earlier evening in the house, a conversation worth keeping."
    ]
  },
  {
    "id": "after-recollection",
    "scenes": [
      "after"
    ],
    "samples": [
      "From an earlier evening in the house, a conversation worth keeping."
    ]
  },
  {
    "id": "reply-recollection",
    "scenes": [
      "reply"
    ],
    "samples": [
      "From an earlier evening in the house, a conversation worth keeping."
    ]
  },
  {
    "id": "old_mark-recollection",
    "scenes": [
      "old_mark"
    ],
    "samples": [
      "From an earlier evening in the house, a conversation worth keeping."
    ]
  }
] as const;
