#!/usr/bin/env node
import fs from 'node:fs';
const source = JSON.parse(fs.readFileSync(new URL('../vocabulary/esdb-2026-09-05.json', import.meta.url), 'utf8'));
// Familiar variant spellings accepted after editorial review. These stay valid
// player words regardless of a spell-checker's preference for another spelling.
const reviewed = new Set(['MOMMA','MOMMAS','SAUTE','SAUTEED','DJINN','SCHEMAS','DIALOGS','TSARIST','FRIER','PRICY','SPACY','FLUKEY','WHACKY','ROPEY','KIDDY']);
const entries = Object.entries(source.levels);
const groups = {
  UNREVIEWED_PUZZLE_WORDS: entries.filter(([w, n]) => n == null && !reviewed.has(w)),
  ADVANCED_PUZZLE_WORDS: entries.filter(([w, n]) => n > 60 && n <= 70 && w !== 'META'),
  OBSCURE_PUZZLE_WORDS: entries.filter(([, n]) => n > 70),
};
let output = '/** Generated by scripts/tools/buildVocabularyPolicy.mjs. Source and license:\n * scripts/vocabulary/esdb-2026-09-05.json; docs/licenses/ESDB-Copyright.txt.\n * This is a puzzle-appearance policy, not a claim that excluded forms are fake.\n */\n';
// Positive source membership makes future additions fail closed until audited.
output += `export const AUDITED_PUZZLE_WORDS = new Set<string>(${JSON.stringify(entries.map(([word]) => word).join(' '))}.split(' '));\n`;
for (const [name, words] of Object.entries(groups)) {
  output += `export const ${name} = new Set<string>(${JSON.stringify(words.map(([w]) => w))});\n`;
}
fs.writeFileSync(new URL('../../src/data/vocabulary/puzzleVocabulary.ts', import.meta.url), output);
console.log(Object.fromEntries(Object.entries(groups).map(([name, words]) => [name, words.length])));
