#!/usr/bin/env node
/** Derive the daily leaderboard cohort from the actual bank data and selection code. */
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import vm from 'node:vm';
import ts from 'typescript';
import { fileURLToPath } from 'node:url';
const root = fileURLToPath(new URL('../..', import.meta.url));
if (process.argv.length > 3 || (process.argv[2] && process.argv[2] !== '--check')) {
  console.error('Usage: node scripts/tools/updateDailyBoardVersion.mjs [--check]');
  process.exit(1);
}
const hash = crypto.createHash('sha256').update('wordshift-daily-cohort-v2');
for (const tier of ['Easy', 'Medium', 'MediumPlus', 'Hard', 'Expert']) {
  const filename = `src/data/puzzleBank${tier}.ts`;
  const source = fs.readFileSync(path.join(root, filename), 'utf8');
  const data = vm.runInNewContext(source.slice(source.indexOf('= [') + 2, source.lastIndexOf('];') + 1), {}, { timeout: 10_000 });
  // Bank order is meaningful: the seeded daily roll selects an array position.
  // Header timestamps and whitespace are not; hash the actual ordered records.
  hash.update(filename).update(JSON.stringify(data));
}
for (const filename of [
  'src/dictionary.ts', 'src/data/vocabulary/puzzleVocabulary.ts',
  'src/services/puzzleVocabulary.ts', 'src/services/bankDeliveryPolicy.ts',
  'src/services/puzzleBank.ts', 'src/services/dailyChallenge.ts', 'src/services/dateUtils.ts',
  'src/constants/gameBalance.ts',
]) {
  const source = fs.readFileSync(path.join(root, filename), 'utf8');
  const normalized = /dictionary\.ts|data\/vocabulary/.test(filename)
    ? source.replace(/\/\*\*[\s\S]*?\*\//g, '').trim()
    : ts.transpileModule(source, { compilerOptions: { module: ts.ModuleKind.ESNext, target: ts.ScriptTarget.ES2020, removeComments: true } }).outputText;
  hash.update(filename).update(normalized);
}
const version = `daily_v2_${hash.digest('hex').slice(0, 16)}`;
const output = `/** Generated by scripts/tools/updateDailyBoardVersion.mjs; checked in CI.\n * Bank content, vocabulary or daily selection changes receive a new cohort.\n */\nexport const DAILY_BOARD_VERSION = '${version}';\n/** Saved boards keep their recorded cohort, including the original legacy one. */\nexport const LEGACY_DAILY_BOARD_VERSION = 'legacy_v1';\n`;
const target = path.join(root, 'src/services/dailyBoardVersion.ts');
if (process.argv[2] === '--check') {
  if (fs.readFileSync(target, 'utf8') !== output) {
    console.error('Daily board cohort is stale. Run node scripts/tools/updateDailyBoardVersion.mjs after bank/selection changes.');
    process.exitCode = 1;
  } else console.log(`Daily cohort verified: ${version}`);
} else {
  fs.writeFileSync(target, output);
  console.log(`Updated daily cohort: ${version}`);
}
